if Vagrant::VERSION < "2.0.0"
  $stderr.puts "Must redirect to new repository for old Vagrant versions"
  Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
end

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS7.5_1804"
  config.vm.box_check_update = false
  #config.vm.synced_folder "shared/", "/shared", create: true
  #config.vm.synced_folder "dataset/", "/dataset", create: true

  config.vm.define "h1" do |server|
    server.vm.provider "virtualbox" do |vb|
	     vb.customize ["modifyvm", :id, "--cpus", "2"]
       vb.name = "hadoop_test01"
       vb.memory = 2048
    end
    server.vm.hostname = "hadoop-test01"
    server.vm.network :public_network, use_dhcp_assigned_default_route: true
    #server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
  end
end
